name: Build
on:
    push:
        branches-ignore:
            - gh-pages
    workflow_dispatch:
    pull_request:
jobs:
    build:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
            - name: Checkout Repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: '0'
                  persist-credentials: false
                  submodules: 'recursive'
            - name: Cache yarn
              uses: c-hive/gha-yarn-cache@v2
              continue-on-error: true
            - name: Install
              run: yarn install
            - name: Build
              run: yarn build
            - name: Run Lighthouse
              uses: treosh/lighthouse-ci-action@v7
              with:
          # no urls needed, since it uses local folder to scan .html files
                configPath: './lighthouserc.json'
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4.4.0
              if: ${{ github.event_name == 'push'}}
              with:
                  branch: result
                  folder: website
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
            - name: Checkout Repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: '0'
                  submodules: 'recursive'
            - name: Cache yarn
              uses: c-hive/gha-yarn-cache@v2
              continue-on-error: true
            - name: Install
              run: yarn install
            - name: Lint
              run: yarn lintci
